# Generated by Django 5.1.6 on 2025-02-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
