# Generated by Django 5.1.6 on 2025-02-22 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_todo_id_alter_todo_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
