# Generated by Django 5.1.6 on 2025-02-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_user_model_id_alter_user_model_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
    ]
