# Generated by Django 5.1.6 on 2025-02-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_todo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='avatar',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
